version: '3'

volumes:
  node_modules_vol:
    driver: local
    driver_opts:
      type: none
      device: "./node_modules"
      o: bind

services:
  bater-ponto:
    image: bater-ponto
    container_name: bater-ponto
    build:
      context: ./.
      dockerfile: ./Dockerfile.dev
    ports:
     - "3434:3434"
     - "4205:4205"
    volumes:
     - ./:/bater-ponto
     - node_modules_vol:/bater-ponto/node_modules
    working_dir: /bater-ponto
