version: '3.1'

services:
  bater-ponto-db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tomate
      MYSQL_DATABASE: baterponto
      MYSQL_USER: devuser
      MYSQL_PASSWORD: tomate
    volumes:
      - ../baterponto-mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"

  bater-ponto-adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080