# download da imagem base
FROM node:16.18.1

# customizações
RUN alias ll="ls -al"

# área de trabalho
WORKDIR /bater-ponto

# instalação das dependências
COPY package.json .
RUN npm install
RUN npm install npx@latest nx@latest -g

# exposição de portas
EXPOSE 3434
EXPOSE 4205

# nenhuma execução
CMD [ "npm", "start" ]
