version: '3'

volumes:
  node_modules_vol:
    driver: local
    driver_opts:
      type: none
      device: "./node_modules"
      o: bind

services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  bater-ponto:
    image: bater-ponto
    container_name: bater-ponto
    tty: true
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile.dev
    ports:
     - "3434:3434"
     - "4205:4205"
     - "9229:9229"
    volumes:
     - ..:/bater-ponto:cached
     - ../../.ssh/:/home/.ssh
     - ../../.gitconfig:/home/.gitconfig
     - node_modules_vol:/bater-ponto/node_modules
    working_dir: /bater-ponto

 
